<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <DisableImplicitFrameworkAttributes>true</DisableImplicitFrameworkAttributes>
      <DisableImplicitAssemblyAttributes>true</DisableImplicitAssemblyAttributes>
      <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="SkiaSharp" Version="3.116.1" />
      <PackageReference Include="System.Text.Json" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.0" />
      <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    </ItemGroup>

      <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
          <_Parameter1>Domain.Tests</_Parameter1>
        </AssemblyAttribute>
      </ItemGroup>

      <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

</Project>
